#!/usr/bin/python3
# @author: Peter Bubestinger-Steindl (aha at ArkThis com)
# @date: 2026-02-03
# Program to generate CFIDs for existing files/data.
# Generated by Mistral AI (2026-02-03)

import os
import datetime
import random
import string

def get_creation_timestamp(file_path):
    """
    Get the creation timestamp of a file using st_birthtime.
    This function is designed for ZFS on Linux.
    """
    stat = os.stat(file_path)
    try:
        return stat.st_birthtime
    except AttributeError:
        # Fallback to modification time if st_birthtime is not available
        return stat.st_mtime


def generate_random_string(max_chars, charset):
    """
    Generate a random string of a specified length and character set.

    :param max_chars: Maximum number of characters in the random string
    :param charset: Character set to use for the random string
    :return: Generated random string
    """
    return ''.join(random.choices(charset, k=max_chars))


def mk_cfid(file_path, max_chars=0, charset=string.ascii_letters + string.digits):
    """
    Generate an ID for a given file based on its creation timestamp, context, and optional random string.

    :param file_path: Path to the file
    :param max_chars: Maximum number of characters in the random string (default is 0, meaning no random string)
    :param charset: Character set to use for the random string (default is alphanumeric)
    :return: Generated ID in the format ⭐️$TIMESTAMP-$CONTEXT-$RANDOM❤️
    """
    # Get the creation timestamp
    timestamp = get_creation_timestamp(file_path)
    timestamp_str = datetime.datetime.fromtimestamp(timestamp).strftime('%Y%m%d%H%M%S')

    # Get the context (parent folder and filename)
    context = os.path.relpath(file_path, start=os.path.dirname(file_path))

    # Generate the random string if max_chars is greater than 0
    random_str = generate_random_string(max_chars, charset) if max_chars > 0 else ""

    # Generate the ID
    cfid = f"⭐️{timestamp_str}-{context}-{random_str}❤️"

    return cfid


# Example usage
if __name__ == "__main__":
    # Change to point to any existing file you'd like a CFID for:
    file_path = "/home/pb/unison.log"

    max_chars = 8  # Example: 8 characters for the random string
    charset = string.ascii_letters + string.digits  # Example: alphanumeric characters
    cfid = mk_cfid(file_path, max_chars, charset)
    print(f"Generated ID: {cfid}")

